Add loop that waits a bit before the service becomes available, make Axis2 plugin more usable

diff --git a/dysnomia-modules/axis2-webservice.in b/dysnomia-modules/axis2-webservice.in
--- a/dysnomia-modules/axis2-webservice.in
+++ b/dysnomia-modules/axis2-webservice.in
@@ -6,6 +6,9 @@ shopt -s nullglob
 # Activates or deactivates web service archives (*.aar files) in the
 # axis2/WEB-INF/services subfolder by symlinking them into an Apache Axis2
 # container.
+#
+# Environment variables:
+# timout: Maximum amount of seconds we should wait for the Axis2 base directory to become available
 
 # Autoconf settings
 export prefix=@prefix@
@@ -16,15 +19,49 @@ source @datadir@/@PACKAGE@/util
 # Sets a number of common utility environment variables
 composeUtilityVariables $0 $2 $3
 
-catalinaBaseDir=@CATALINA_BASE@
+if [ "$catalinaBaseDir" = "" ]
+then
+    catalinaBaseDir=@CATALINA_BASE@
+fi
+
+if [ "$axis2BaseDir" = "" ]
+then
+    axis2BaseDir=@CATALINA_BASE@/webapps/axis2/WEB-INF/services
+fi
+
+timeout=${timeout:-10}
 
 case "$1" in
     activate)
+        # Wait for the Axis2 deployment directory to become available
+        numOfTries=1
+        detectedAxis2BaseDir=0
+
+        while [ $numOfTries -lt $timeout ]
+        do
+            echo "Waiting for the Axis2 base directory to become available..." >&2
+
+            if [ -d "$axis2BaseDir" ]
+            then
+                detectedAxis2BaseDir=1
+                break
+            fi
+
+            sleep 1
+            ((numOfTries++))
+        done
+
+        if [ "$detectedAxis2BaseDir" = "0" ]
+        then
+            echo "The Axis2 base directory did not appear within $timeout seconds! Failing..." >&2
+            exit 1
+        fi
+
         # Link all AAR files in the deployment directory, so that they will be activated with hot-deployment
         find $(@readlink@ -f $2/webapps/axis2/WEB-INF/services) -name \*.aar | while read i
         do
             # Link the web service
-            ln -sfn $i $catalinaBaseDir/webapps/axis2/WEB-INF/services/`basename $i`
+            ln -sfn $i $axis2BaseDir/`basename $i`
 
             # Link the configuration files if they exist
             if [ -d $2/conf/Catalina ]
@@ -45,7 +82,7 @@ case "$1" in
         find $(@readlink@ -f $2/webapps/axis2/WEB-INF/services) -name \*.aar | while read i
         do
             # Remove the web service
-            rm -f $catalinaBaseDir/webapps/axis2/WEB-INF/services/`basename $i`
+            rm -f $axis2BaseDir/`basename $i`
 
             # Also remove the configuration files if they exist
             if [ -d $2/conf/Catalina ]
@@ -62,6 +99,11 @@ case "$1" in
     shell)
         cat >&2 <<EOF
 This is a shell session that can be used to control the '$componentName' Axis2 webservice.
+
+Module specific environment variables:
+componentName    Name of the application
+axis2BaseDir     Directory in which AAR archives are deployed
+catalinaBaseDir  Directory in which the Servlet container resides
 EOF
         ;;
 esac
diff --git a/dysnomia-modules/mysql-database.in b/dysnomia-modules/mysql-database.in
--- a/dysnomia-modules/mysql-database.in
+++ b/dysnomia-modules/mysql-database.in
@@ -32,14 +32,43 @@ then
     socketArg="--socket=$mysqlSocket"
 fi
 
+timeout=${timeout:-10}
+
 case "$1" in
     activate)
+        if [ "$mysqlSocket" != "" ]
+        then
+            # Wait for socket file to become available
+            numOfTries=1
+            detectedSocketFile=0
+
+            while [ $numOfTries -lt $timeout ]
+            do
+                echo "Waiting for the MySQL socket file to become available..." >&2
+
+                if [ -e "$mysqlSocket" ]
+                then
+                    detectedSocketFile=1
+                    break
+                fi
+
+                sleep 1
+                ((numOfTries++))
+            done
+
+            if [ "$detectedSocketFile" = "0" ]
+            then
+                echo "Could not detect MySQL socket file within $timeout seconds! Failing..." >&2
+                exit 1
+            fi
+        fi
+
         # Initalize the given schema if the database does not exists
         if [ "$(echo "show databases" | @mysql@ $socketArg --user=$mysqlUsername --password=$mysqlPassword -N | grep -x $componentName)" = "" ]
         then
             ( echo "create database $componentName;"
               echo "use $componentName;"
-              
+
               if [ -d $2/mysql-databases ]
               then
                   cat $2/mysql-databases/*.sql
@@ -58,12 +87,12 @@ case "$1" in
         # line because that contains a comment with a timestamp Without it we
         # can compare output hashes to see whether dumps are identical
         @mysqldump@ $socketArg --single-transaction --quick --user=$mysqlUsername --password=$mysqlPassword $componentName | head -n-1 | xz > dump.sql.xz
-        
+
         hash=$(cat dump.sql.xz | sha256sum)
         hash=${hash:0:64}
-        
+
         snapshotsPath=$(composeSnapshotsPath)
-        
+
         if [ -d $snapshotsPath/$hash ]
         then
             rm -Rf $tmpdir
@@ -76,7 +105,7 @@ case "$1" in
         ;;
     restore)
         lastSnapshot=$(determineLastSnapshot)
-        
+
         if [ "$lastSnapshot" != "" ]
         then
             ( echo "use $componentName;"
diff --git a/dysnomia-modules/tomcat-webapplication.in b/dysnomia-modules/tomcat-webapplication.in
--- a/dysnomia-modules/tomcat-webapplication.in
+++ b/dysnomia-modules/tomcat-webapplication.in
@@ -9,6 +9,7 @@ shopt -s nullglob
 #
 # Container properties (environment variables):
 # catalinaBaseDir: Base directory in which Apache Tomcat is installed (defaults to: @CATALINA_BASE@)
+# timout: Maximum amount of seconds we should wait for the webapps base directory to become available
 
 # Autoconf settings
 export prefix=@prefix@
@@ -24,8 +25,34 @@ then
     catalinaBaseDir=@CATALINA_BASE@
 fi
 
+timeout=${timeout:-10}
+
 case "$1" in
     activate)
+        # Wait for the webapps deployment directory to become available
+        numOfTries=1
+        detectedWebappsBaseDir=0
+
+        while [ $numOfTries -lt $timeout ]
+        do
+            echo "Waiting for the webapps base directory to become available..." >&2
+
+            if [ -d "$catalinaBaseDir/webapps" ]
+            then
+                detectedWebappsBaseDir=1
+                break
+            fi
+
+            sleep 1
+            ((numOfTries++))
+        done
+
+        if [ "$detectedWebappsBaseDir" = "0" ]
+        then
+            echo "The webapps base directory did not appear within $timeout seconds! Failing..." >&2
+            exit 1
+        fi
+
         # Link all WAR files in the deployment directory, so that they will be activated with hot-deployment
         find $(@readlink@ -f $2/webapps) -name \*.war | while read i
         do
@@ -66,6 +93,10 @@ case "$1" in
     shell)
         cat >&2 <<EOF
 This is a shell session that can be used to control the '$componentName' Tomcat web application.
+
+Module specific environment variables:
+componentName    Name of the application
+catalinaBaseDir  Directory in which the Servlet container resides
 EOF
         ;;
 esac
