Re-add workaround for slow terminating processes, fix systemd-unit testcase

diff --git a/dysnomia-modules/util b/dysnomia-modules/util
--- a/dysnomia-modules/util
+++ b/dysnomia-modules/util
@@ -473,3 +473,32 @@ waitForSocket()
 {
     waitForAnyFileType "$1" "$2" "S"
 }
+
+# Attempts to execute a command and retries it a given number of times if it
+# fails.
+#
+# Parameters:
+# $1: Command to execute
+# $2: The amount of times to retry if the command fails
+
+attemptSeveralTimes()
+{
+    local num=0
+    while [ $num -lt $2 ]
+    do
+        if $1
+        then
+            break
+        fi
+
+        echo "Commmand failed, trying again in a second..." >&2
+        sleep 1
+        num=$((num + 1))
+    done
+
+    if [ $num -eq $2 ]
+    then
+        echo "Still does not work after $num attempts!" >&2
+        false
+    fi
+}
